modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU General Public License v3.0"
[[mods]] #mandatory

modId="clinker" #mandatory

version="1.16.1 - 1.0" #mandatory

displayName="Clinker" #mandatory

# updateJSONURL="http://myurl.me/" #optional

# displayURL="http://example.com/" #optional

logoFile="logo.png" #optional

authors="cappin" #optional

	# The description text for the mod (multi line!) (#mandatory)
description='''
The mysteries and majesties of alchemy have finally opened!
'''

	# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
#[[dependencies.examplemod]] #optional
    # the modid of the dependency
#    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
#    mandatory=true #mandatory
    # The version range of the dependency
#    versionRange="[31,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
#    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
#    side="BOTH"

[[dependencies.clinker]] #optional
    modId="ctm" #mandatory
    mandatory=false #mandatory
    versionRange="[31,)" #mandatory
    ordering="BEFORE"
    side="BOTH"
