modLoader="javafml"

loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/birsy/clinker-mod/issues"

[[mods]]

modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# (in the root of the mod JAR)
logoFile="logo.png" #optional
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="veil"
    type = "required"
    versionRange="[1.0,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="smartbrainlib"
    type = "required"
    versionRange="[1.16,)"
    ordering="NONE"
    side="SERVER"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
